services:
  stillness:
    build: .
    container_name: stillness
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PORT=3000
    volumes:
      - ./data:/app/data # Used for cache persistence
